# Site settings
title: w0lker
description:
baseurl: ""
url: "http://www.w0lker.com"

author:
  github: w0lker
  email: w0lker.tg@gmail.com

# google_analytics: 'UA-71881782-1'
baidu_analytics: '722e76bcde4126eafcafc23bb5a40f32'

# Build settings
markdown: kramdown

# Outputing
timezone: Asia/Harbin

theme: jekyll-theme-minimal