# Site settings
title: w0lker
description:
baseurl: ""
url: "http://w0lker.github.io"

author:
  fullname: w0lker_tg
  googleplus:
  github: w0lker
  twitter: w0lker_tg
  disqus: w0lker
  email: w0lker_tg@gmail.com

# Build settings
markdown: kramdown

# Outputing
timezone: Asia/Beijing
